name = "DeflatedWaveHoltz"
uuid = "af1cf9b0-8caa-48c3-ba7e-2b5e22823834"
authors = ["Daniel Appelo <appelo@vt.edu>"]
version = "0.0.1"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AlgebraicMultigrid = "1.1.0"
ArnoldiMethod = "0.4.0"
CairoMakie = "0.15.6"
GLMakie = "0.13.6"
InvertedIndices = "1.3.1"
IterativeSolvers = "0.9.4"
JLD2 = "0.6.2"
LaTeXStrings = "1.4.0"
LinearMaps = "3.11.4"
Meshes = "0.55.0"
Plots = "1.40.9"
Revise = "3.12.1"
SparseArrays = "1.11.0"
SummationByPartsOperators = "0.5.74"
TimerOutputs = "0.5.29"
